// Generated by scripts/sync-ranked-engine.mjs. Do not edit.
/** Initial tuning values, shared by the engine and its numerical tests. */
export const BALANCE = Object.freeze({
  fixedDt: 1 / 120,
  maxTickSeconds: 1 / 30,
  timerEpsilon: 1e-9,
  criticalAngleRad: 1.134464014, // 65 degrees, aligned to the 1e-9 replay grid.
  controlAcceleration: 9.6,
  damping: 1.8,
  countdownSeconds: 3,
  mockAdSeconds: 5,
  protectionSeconds: 1.5,
  stabilizationRate: 4,
  warningSeconds: 1.2,
  activeEventSeconds: 0.7,
  wobbleCooldownSeconds: 1.5,
  baseSpeedMps: 0.9193552309022899,
  footstepBaseSeconds: 0.3,
  minFootstepSeconds: 0.12,
  firstEventDelaySeconds: 2,
});
