// Generated by scripts/sync-ranked-engine.mjs. Do not edit.
export type Direction = -1 | 1;
export type Stage = 'street' | 'office';
export type Screen = 'title' | 'countdown' | 'playing' | 'paused' | 'ad' | 'result';
export type InputState = Readonly<{ left: boolean; right: boolean }>;
export type EventId = 'coffeeRush' | 'lateCommute' | 'urgentEdit' | 'bossCall' | 'longMeeting';

export interface WorkEvent {
  id: EventId;
  direction: Direction;
  phase: 'warning' | 'active';
  remainingSeconds: number;
  strength: number;
}

/** Pure gameplay values: radians, seconds and meters; no device or wall-clock state. */
export interface RunState {
  id: number;
  seed: number;
  rng: number;
  distanceM: number;
  elapsedSeconds: number;
  angleRad: number;
  angularVelocity: number;
  hasCoffee: boolean;
  reviveUsed: boolean;
  protectionSeconds: number;
  event: WorkEvent | null;
  nextEventAt: number;
  stepIndex: number;
  nextFootstepAt: number;
  lastWobbleAt: number;
}

export interface GameState {
  screen: Screen;
  run: RunState | null;
  resumeTo: 'playing' | 'countdown' | 'ad' | null;
  countdownSeconds: number;
  adSeconds: number;
}

export type GameAction =
  | { type: 'START'; runId: number; seed: number }
  | { type: 'TICK'; dt: number; input: InputState }
  | { type: 'PAUSE' }
  | { type: 'RESUME' }
  | { type: 'HOME' }
  | { type: 'REQUEST_AD' }
  | { type: 'CANCEL_AD' };

export type GameEffect =
  | { type: 'footstep' | 'wobble' | 'coffee' | 'fall' | 'revive'; runId: number }
  | { type: 'eventWarning'; runId: number; eventId: EventId; direction: Direction };

export interface Transition {
  state: GameState;
  effects: GameEffect[];
}

export interface Difficulty {
  level: number;
  speedMps: number;
  instability: number;
  disturbance: number;
  eventStrength: number;
  eventIntervalSeconds: number;
}
